services:
  postgres:
    container_name: postgres-database-server
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    container_name: redis-server
    image: redis

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
      - client

  api:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres

  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis

  client:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
    environment:
      - WDS_SOCKET_PORT=0
